name: sismondi_nft

contracts-folder: "contracts"

plugins:
  - name: solidity
    version: 0.7.0
  - name: hardhat
  - name: ens
  - name: etherscan
    version: ">=0.7.0,<0.8"
  - name: ape-ganache

# dependencies:
#   - OpenZeppelin/openzeppelin-contracts@4.4.1

