name: sismondi_nft

contracts-folder: "contracts"

plugins:
  - name: solidity
    version: 0.6.0
  - name: hardhat
  - name: ens
  - name: etherscan
    version: ">=0.6.2,<0.7"
  - name: ape-ganache

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1

